### ISSUE TITLE
Bone Animation Support

### ISSUE THREAD

**Issue by wpitallo** [brinsleylogic/pixi-spriter#1]
Awesome project! Had to make a few changes to get it working but managed to get an animation loading. One thing I noticed tho is it not seem to animate the bones? Is that currently supported?

**Comment by brinsleylogic** [comment]
Hey, thanks for checking it out. It's been a while since I looked at it but jyst looking through the code it _seems_ as though the bones _should_ also be animating. The [`applyParentTransforms`](https://github.com/brinsleylogic/pixi-spriter/blob/f53de639a4eeb4af6b1c96fd9269ba24374949dd/src/animator/animation/AnimationUtils.ts#L73) is what updates the components based on their parent's transforms. This assumes that everything is parented to a bone, i.e.

For every frame:
* It starts with the root bone's transform.
* Loops all of the other bones and updates their transforms base don their parent bone.
* Loops all of the objects (sprites) and updates their transforms based on their parent bone's transform (as calculated in the previous step).

If you're seeing transform updates (positions, rotations, scaling) then that _should_ be indicative that the bones are animating. If that's not the case could you throw together an example project and I'll check it out :)

**Comment by wpitallo** [comment]
Hey thanks so so much, 

Ok cool I understand a bit more now thank you, yes so it looks like the bones are working but I think i may just be a propery transform missing maye for and angle or something (not 100% sure) .

I have created a small video to show you here:

https://user-images.githubusercontent.com/12214559/136669331-d68783d2-f45b-442a-a735-a7a3553864a3.mp4

And I made a fork of you repo with my changes here:

https://github.com/wpitallo/pixi-spriter

I also noticed that on the "idle" animation it also seems do something wierd with the eyes in this example. It seems like the first eye does not scale correctly and then also the pupils dont dissapear on the blink. 

https://user-images.githubusercontent.com/12214559/136669949-2e574184-7679-4780-8acd-5c82468555ff.mp4

Jeepers if you could help out with this or point me in the right direction it would be greatly appreciated. I have not ever worked that with bones etc so I am not entirly sure how its all supposed to fit together.

Thanks so so much again, really apriciate it and awesome job! Been searching everywhere for a way to get spriter working with PIXI.

**Comment by wpitallo** [comment]
A bit of a side note :) do you work at Microgaming Switch Studios ?

**Comment by brinsleylogic** [comment]
I've spent a couple of hours looking through the project and it the weirdest thing I'm seeing is that the values in the scon file don't match up to what I'm seeing actually in Spriter - even when I save the file myself, which is super weird. Maybe the difference between your project set up and my demo stuff is that my scon files were generated when generating a Spritesheet - maybe it does something different with the transform data? I tried to get your project exported in the same way but the `Ok` button is disabled whenever I try 😢 

I'll take a look when I get more time but I can't otherwise see any obvious reason why it would break. I'll need to figure out a nice way to debug stuff like this 😂

**Comment by wpitallo** [comment]
Hey thanks again so much, really appreciate the help. So i did make a few changes to the loader code: 

I added the extra step to load the individual files rahter than the atlas. Wander is thats maybe causing an issue downstream?

```javascript
        // Check for loading spritesheets.
        data.folder.forEach((atlas) => {  //not really an atlas anymore (in this case, should have probably named "folder")
            atlas.file.forEach((file) => {
                const url = atlasPath + file.name;

                if (!loader.resources[url]) {
                    loader.add(file.name, url, loaderOptions);
                }
            });
        });
```

**Comment by brinsleylogic** [comment]
Managed to rule out the spritesheet differences - needed to massive increase the output size of the spritesheets - it still breaks. I'm gonna raise 2 bugs and a feature request off the back of this as there are a couple of weird things going on here. I'm not sure how quickly I'll be able to turn around a fix (I'm still not 10% sure what's going wrong) but I'll keep you posted.

**Comment by brinsleylogic** [comment]
Raised:

https://github.com/brinsleylogic/pixi-spriter/issues/2
https://github.com/brinsleylogic/pixi-spriter/issues/3
https://github.com/brinsleylogic/pixi-spriter/issues/4
https://github.com/brinsleylogic/pixi-spriter/issues/5

**Comment by wpitallo** [comment]
Thanks so much @brinsleylogic, really appreciate the help!
